title: TimeOut Chef Recipes
description: Family recipes made between timeouts.
url: https://timeoutchef.com

collections:
  recipes:
    output: true
    permalink: /recipes/:name/

defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe

markdown: kramdown
