title: TimeOut Chef Recipes
description: Family recipes made between timeouts.

collections:
  recipes:
    output: true
    permalink: /recipes/:name/

defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe

markdown: kramdown

